theme: jekyll-theme-cayman

# Theme setup
title:        Simple Three
tagline:      A 2D developer friendly collection of addons for Construct 2
baseurl: https://jeydotc.github.io/construct2-simplethree
paginate:     1
locale:       "en"